name = "urometoden"
compatibility_date = "2024-11-01"
pages_build_output_dir = "./dist"

[[r2_buckets]]
binding = 'AUDIO_BUCKET'
bucket_name = 'audio-files'

[[d1_databases]]
binding      = 'DB'
database_name = 'urometoden-db'
database_id   = '05016167-addb-4aeb-81f4-3cff81bc88e7'